name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: aichat
            asset_name: aichat-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: aichat.exe
            asset_name: aichat-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: aichat
            asset_name: aichat-macos-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: aichat
            asset_name: aichat-macos-arm64

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/aichat-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
